name: PHP Tests

on:
  workflow_call:
    inputs:
      safe-checkout:
        required: true
        description: "The SHA key for the commit we want to run over"
        type: string

permissions:
  contents: read

jobs:
  macos:
    strategy:
      fail-fast: false   # Don't cancel all jobs if one fails.
      matrix:
        version: ['7.4', '8.0']
        noop: [0,1,2,3,4,5]

    name: MacOS PHP ${{ matrix.version }}
    runs-on: macos-12
    env:
      BAZEL_OSX_EXECUTE_TIMEOUT: 60
    steps:
      - name: Checkout pending changes
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ inputs.safe-checkout }}
          submodules: recursive

      - name: Uninstall problematic libgd
        run: brew uninstall --ignore-dependencies gd

      - name: Install dependencies
        run: brew install coreutils gd

      - name: Pin PHP version
        uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d # 2.24.0
        with:
          php-version: ${{ matrix.version }}

      - name: Check PHP version
        run: php --version | grep ${{ matrix.version }} || (echo "Invalid PHP version - $(php --version)" && exit 1)

      - name: Setup composer
        uses: protocolbuffers/protobuf-ci/composer-setup@v1
        with:
          cache-prefix: php-${{ matrix.version }}
          directory: php

      - name: Run tests
        uses: protocolbuffers/protobuf-ci/bazel@v1
        with:
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: php_macos/${{ matrix.version }}
          version: '6.1.0'
          bash: |
            pushd php
            php -v
            php -m
            composer update
            composer test_c
            popd

      - name: Run conformance tests
        uses: protocolbuffers/protobuf-ci/bazel@v1
        with:
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: php_macos/${{ matrix.version }}
          version: '6.1.0'
          bash: >-
            bazelisk $BAZEL_STARTUP_FLAGS \
              test $BAZEL_FLAGS \
              --action_env=PATH --test_env=PATH \
              //php:conformance_test_c
